site_name: CAIXA
docs_dir: gitpages/docs
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-CAIXA
repo_name: CAIXA

nav:
  - In√≠cio: index.md
  - Atas: atas.md
  - Planejamento:
    - Sites avaliados: planejamento/avaliados.md
    - Site selecionado: planejamento/selecionado.md
    - Ferramentas do projeto: planejamento/ferramentas.md
    - Cronograma planejado: planejamento/cronograma_plan.md
    - Processo de design: planejamento/processo.md
  - Entregas: entregas.md

extra_css:
  - css/custom.css


theme:
  name: 'material'
  language: 'pt'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro 
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.numbered
  search: true
  search_index_only: ['content']

  icon:
    repo: fontawesome/brands/github
  logo: ./img/caixa-icon.png
